name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo chown ubuntu:ubuntu /home/***/.pm2/rpc.sock /home/***/.pm2/pub.sock
            cd git-action-ec2-deploy-test
            pm2 stop 0
            git pull origin main
            npm i
            pm2 restart 0
