name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Connect to EC2 instance
        if:
          github.event.pull_request.merged == true || github.event_name ==
          'push'
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pm2 stop all
            cd git-action-ec2-deploy-test
            git pull origin main
            npm i
            pm2 restart all
