name: Deploy to EC2

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Connect to EC2 instance
        if: github.event.pull_request.merged == true
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pm2 stop all
            cd git-action-ec2-deploy-test
            git checkout ${{ github.event.pull_request.base.ref }}
            git pull origin ${{ github.event.pull_request.base.ref }}
            npm i
            pm2 restart all
